name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: python scripts/bitbucket-pipeline-setup.py

    - name: Build
      run: west build -b my_custom_board -s app -p

  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Environment
      run: python scripts/bitbucket-pipeline-setup.py

    - name: Run Tests
      run: west twister -T app/tests --integration
